export const GET_VEHICLES = "GET_VEHICLES";
export const GET_VEHICLES_GPS = "GET_VEHICLES_GPS";
export const GET_RUNS = "GET_RUNS";
export const GET_RUN_TRIPS = "GET_RUN_TRIPS";
export const GET_TRIP_STOPS = "GET_TRIP_STOPS";
export const SELECT_GPS = "SELECT_GPS";
export const GET_ROUTES = "GET_ROUTES";
export const GET_ROUTE_PATTERNS = "GET_ROUTE_PATTERNS";
export const GET_ACTUAL_STOPS = "GET_ACTUAL_STOPS";
export const GET_ACTUAL_PROBLEMS = "GET_ACTUAL_PROBLEMS";

export const GET_PATTERN_ETA_ANALYTICS = "GET_PATTERN_ETA_ANALYTICS";
export const GET_STOP_ETA_ANALYTICS = "GET_STOP_ETA_ANALYTICS"

export const SET_ACTIVE_DATE = "SET_ACTIVE_DATE";
export const SET_THRESHOLD = "SET_THRESHOLD";